[project]
name = "ccbus"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "flair>=0.15.1",
    "jsonlines>=4.0.0",
    "neo4j>=6.0.3",
    "nltk>=3.9.2",
    "ollama>=0.6.1",
    "pandas>=2.3.3",
    "scrapy>=2.13.4",
]
